# Generated by Django 4.1.5 on 2023-04-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_posts_child_comments_posts_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='child_comments',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='posts',
            name='child_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments_lists', to='network.posts'),
        ),
        migrations.AddField(
            model_name='posts',
            name='parent_comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='network.posts'),
        ),
    ]
