# Generated by Django 4.1.5 on 2023-04-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_posts_child_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='original_post',
            field=models.BooleanField(default=True),
        ),
    ]
