# Generated by Django 4.1.5 on 2023-05-02 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_posts_original_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='child_comments',
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_likes',
            field=models.ManyToManyField(blank=True, related_name='list_of_post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='child_comments',
            field=models.ManyToManyField(blank=True, related_name='ListofChildComments', to='network.posts'),
        ),
    ]
