# Generated by Django 4.1.5 on 2023-05-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_posts_child_comments_alter_posts_post_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='child_comments',
            new_name='childcomments',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='original_post',
            new_name='originalpost',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='parent_comment',
            new_name='parentcomment',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_likes',
            new_name='postlikes',
        ),
    ]
