# Generated by Django 4.1.5 on 2023-05-10 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rename_child_comments_posts_childcomments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='parentcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='network.posts'),
        ),
    ]
