# Generated by Django 4.1.5 on 2023-01-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_item_comments_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="end_date",
        ),
    ]
