# Generated by Django 4.1.5 on 2023-01-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_remove_item_end_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="image",
            new_name="image_file",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
