# Generated by Django 4.1.5 on 2023-01-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auctions",
            "0004_rename_image_item_image_file_rename_name_item_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="static/items/"),
        ),
    ]
