# Generated by Django 4.1.5 on 2023-01-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_item_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
