# Generated by Django 4.1.5 on 2023-01-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="watchlist_item",
            new_name="item",
        ),
    ]
