# Generated by Django 4.1.5 on 2023-01-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_item_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
